package br.com.brunotonia.soap.view;

import br.com.brunotonia.soap.CarroServidor;
import br.com.brunotonia.soap.util.JTableUtil;
import br.com.brunotonia.soap.vo.Carro;
import java.net.URL;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;

public class Principal extends javax.swing.JFrame {

    /* Variáveis de Sessão */
    private Carro[] lista = null;

    private void povoarTblCarros() {
        tblCartas.setModel(new JTableUtil().geraTabelaCartas(lista));
        if (lista != null) { 
            tblCartas.getColumnModel().getColumn(0).setPreferredWidth(90);
            tblCartas.getColumnModel().getColumn(1).setPreferredWidth(80);
            tblCartas.getColumnModel().getColumn(2).setPreferredWidth(80);
            tblCartas.getColumnModel().getColumn(3).setPreferredWidth(80);
            tblCartas.getColumnModel().getColumn(4).setPreferredWidth(55);
            tblCartas.getColumnModel().getColumn(5).setPreferredWidth(65);
            tblCartas.getColumnModel().getColumn(6).setPreferredWidth(50);
            tblCartas.getColumnModel().getColumn(7).setPreferredWidth(65);
            tblCartas.getColumnModel().getColumn(8).setPreferredWidth(65);
        } else {

        }
        tblCartas.setColumnSelectionAllowed(false);
    }

    /**
     * Creates new form Enciclopédia
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEnciclopedia = new javax.swing.JLabel();
        lblResultados = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCartas = new javax.swing.JTable();
        btnVisualizar = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();
        btnAdicionar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cliente SOAP - Carros");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        lblEnciclopedia.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblEnciclopedia.setText("Cliente SOAP - Carros");

        lblResultados.setText("Lista de Carros");

        tblCartas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        tblCartas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCartasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCartas);

        btnVisualizar.setText("Visualizar Carta");
        btnVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizarActionPerformed(evt);
            }
        });

        btnAtualizar.setText("Atualizar Lista");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        btnAdicionar.setText("Adicionar Carro");
        btnAdicionar.setToolTipText("");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 926, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAdicionar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAtualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnVisualizar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEnciclopedia)
                            .addComponent(lblResultados))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEnciclopedia)
                .addGap(26, 26, 26)
                .addComponent(lblResultados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVisualizar)
                    .addComponent(btnAtualizar)
                    .addComponent(btnAdicionar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblCartasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCartasMouseClicked

    }//GEN-LAST:event_tblCartasMouseClicked

    private void btnVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizarActionPerformed
        // TODO add your handling code here:
        Integer i = tblCartas.getSelectedRow();
        if (i != -1) {
            // TODO add your handling code here:
            URL url = null;
            try {
                url = new URL("http://127.0.0.1:9876/carro?wsdl");
            } catch (Exception e) {

            }
            QName qname = new QName("http://soap.brunotonia.com.br/", "CarroServidorImplService");
            Service ws = Service.create(url, qname);
            CarroServidor carroSrv = ws.getPort(CarroServidor.class);
            Carro carro = carroSrv.buscar(lista[i].getId());
            new CarroView(this, carro).setVisible(true);
        }
    }//GEN-LAST:event_btnVisualizarActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        // TODO add your handling code here:
        URL url = null;
        try {
            url = new URL("http://127.0.0.1:9876/carro?wsdl");
            QName qname = new QName("http://soap.brunotonia.com.br/", "CarroServidorImplService");
            Service ws = Service.create(url, qname);
            CarroServidor carroSrv = ws.getPort(CarroServidor.class);
            lista = carroSrv.listar();
            povoarTblCarros();
        } catch (Exception ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        // TODO add your handling code here:
        new CadastrarView(this).setVisible(true);
    }//GEN-LAST:event_btnAdicionarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnVisualizar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEnciclopedia;
    private javax.swing.JLabel lblResultados;
    private javax.swing.JTable tblCartas;
    // End of variables declaration//GEN-END:variables
}
